name: Release Workflow

on:
  push:
    branches:
      - release

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Extract version from eedl package
        id: get_version
        run: echo "::set-output name=version::$(python -c "from eedl import __version__; print(__version__)")"


      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
          env:
            GH_TOKEN: ${{ github.token }}

        with:
          title: ${{ steps.get_version.outputs.version }}
