name: Release Workflow

on:
  push:
    branches:
      - release

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Extract version from eedl package
        id: get_version
        run: |
          version=$(python -c "from eedl import __version__; print(__version__)")
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Build WHL file
        run: |
          pip install setuptools wheel
          python setup.py bdist_wheel

      - name: Create and attach whl to Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create -t "${{ env.VERSION }}" ./dist/*.whl --generate-notes
