name: Release Workflow

on:
  push:
    branches:
      - release

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Extract version from eedl package
        id: get_version
        run: |
          version=$(python -c "from eedl import __version__; print(__version__)")
          echo "VERSION=$version" >> $GITHUB_ENV


      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ github.token }}

        with:
          title: ${{ env.VERSION }}