name: Version bump

on:
  push:
    branches:
      - 'release'
  pull_request:
    branches:
      - 'release'

jobs:
  Version-Check:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python Ubuntu
        uses: actions/setup-python@v4
        if: matrix.os ==  'ubuntu-latest'
        with:
          python-version: 3.11

      - name: Get the version number from setup.cfg
        run: |
          setupcfg_version=$(grep -oP 'version\s*=\s*\K[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' setup.cfg)
          echo "SETUPCFG_VERSION=$setupcfg_version" >> $GITHUB_ENV

      - name: Check version is increased
        run: |
          python -m pip install requests
          python -c "import requests;import re;import os;latest=requests.get('https://pypi.org/pypi/eedl/json').json()['info']['version'];import eedl;version_number=eedl.__version__;setupcfg_version=os.environ.get('SETUPCFG_VERSION');assert (version_number==setupcfg_version and version_number>latest);version_pattern = re.compile(r'^0\.202[1-9]\.(1[0-2]|[1-9])\.(3[01]|[12][0-9]|[1-9])$');assert version_pattern.match(version_number)"
